# This file was generated by GoReleaser. DO NOT EDIT.
cask "celeris" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "985590da7c20b817e3c8a501faaf1f9611b534912bafd3b109aa809d7d8e4644"
      url "https://github.com/ai-celeris/celeris-cli/releases/download/v#{version}/celeris_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "244a1ead0419e30bceebaa78039ea4a59e155bbccb2bdf5541aaa12e23578700"
      url "https://github.com/ai-celeris/celeris-cli/releases/download/v#{version}/celeris_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0ab9f242f17e01c55e15b767098abade9ad785faa22f4d2e777638c902f371ce"
      url "https://github.com/ai-celeris/celeris-cli/releases/download/v#{version}/celeris_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6007fc7dd2da5994fd49d2333a7399f8a5c21e84e75012b29ba7b04b97018488"
      url "https://github.com/ai-celeris/celeris-cli/releases/download/v#{version}/celeris_#{version}_linux_arm64.tar.gz"
    end
  end

  name "celeris"
  desc "Command-line interface for the Celeris inference API"
  homepage "https://docs.celeris.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "celeris"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/celeris"]
    end
  end

  # No zap stanza required

end
