# This file was generated by GoReleaser. DO NOT EDIT.
cask "celeris" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "aaebd16e60a8f720face94e15460e9ccb2ad5bcc679eb15f47e6c96160c3d852"
      url "https://github.com/ai-celeris/celeris-cli/releases/download/v#{version}/celeris_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "91e1521e2addc42333e1b3356a5ea39c43c87f2857de58d624c96f603c25f149"
      url "https://github.com/ai-celeris/celeris-cli/releases/download/v#{version}/celeris_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fd09650b07788d6bfc61132d910ff484d43d457e49b62ee9df3defc313cf30e4"
      url "https://github.com/ai-celeris/celeris-cli/releases/download/v#{version}/celeris_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "063dd32b563781721ad1f08aadca6d661d2b54d79842138dfbdb11fec19ac448"
      url "https://github.com/ai-celeris/celeris-cli/releases/download/v#{version}/celeris_#{version}_linux_arm64.tar.gz"
    end
  end

  name "celeris"
  desc "Command-line interface for the Celeris inference API"
  homepage "https://docs.celeris.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "celeris"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/celeris"]
    end
  end

  # No zap stanza required

end
